version: '2'

services:
    web:
        build: ./docker/nginx
        ports:
            - "8008:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs/:/var/log/nginx/
            
    mysql:
        image: mysql:5.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        expose:
            - 3306
        volumes:
            - ./docker/mysql:/var/lib/mysql/   

    phpfpm:
        build: ./docker/phpfpm
        expose:
            - 9000
        volumes:
            - ./:/var/www/html
        links:
            - maildev
        environment:
            DATABASE_URL: "mysql://root:root@mysql:3306/test-technique"
            APP_ENV: dev
            
    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        restart: always
        ports:
            - '8080:80'
        links:
            - mysql:mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306

    maildev:
        image: djfarrelly/maildev
        ports:
            - "8081:80"
        